# Generated by Django 5.1 on 2025-05-02 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名前")),
                ("text", models.TextField(verbose_name="本文")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.comment",
                        verbose_name="コメント",
                    ),
                ),
            ],
            options={
                "verbose_name": "返信",
                "verbose_name_plural": "返信",
            },
        ),
    ]
