# Generated by Django 5.1 on 2025-05-02 06:21

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(verbose_name="本文"),
        ),
    ]
